# Open file
[[mgr.prepend_keymap]]
on = [ "o" ]
run = "open --interactive"
desc = "Open files by nvim/vscode"

[[manager.prepend_keymap]]
on   = [ "c" ]
run  = "open --launch open_vscode"
desc = "VSCodeで開く (ファイル/フォルダ共通)"

[[manager.prepend_keymap]]
on   = "p"
run = 'shell --block -- pause'
desc = "Test"

# yamb.yazi (bookmark)
[[mgr.prepend_keymap]]
on = [ "b", "a" ]
run = "plugin yamb -- save"
desc = "Add bookmark"

[[mgr.prepend_keymap]]
on = [ "b", "g" ]
run = "plugin yamb -- jump_by_key"
desc = "Jump bookmark by key"

[[mgr.prepend_keymap]]
on = [ "b", "G" ]
run = "plugin yamb -- jump_by_fzf"
desc = "Jump bookmark by fzf"

[[mgr.prepend_keymap]]
on = [ "b", "d" ]
run = "plugin yamb -- delete_by_key"
desc = "Delete bookmark by key"

[[mgr.prepend_keymap]]
on = [ "b", "D" ]
run = "plugin yamb -- delete_by_fzf"
desc = "Delete bookmark by fzf"

[[mgr.prepend_keymap]]
on = [ "b", "A" ]
run = "plugin yamb -- delete_all"
desc = "Delete all bookmarks"

[[mgr.prepend_keymap]]
on = [ "b", "r" ]
run = "plugin yamb -- rename_by_key"
desc = "Rename bookmark by key"

[[mgr.prepend_keymap]]
on = [ "b", "R" ]
run = "plugin yamb -- rename_by_fzf"
desc = "Rename bookmark by fzf"

# bookmarks.yazi
[[mgr.prepend_keymap]]
on = [ "m", "a" ]
run = "plugin bookmarks save"
desc = "Save current position as a bookmark"

[[mgr.prepend_keymap]]
on = [ "'" ]
run = "plugin bookmarks jump"
desc = "Jump to a bookmark"

[[mgr.prepend_keymap]]
on = [ "m", "d" ]
run = "plugin bookmarks delete"
desc = "Delete a bookmark"

[[mgr.prepend_keymap]]
on = [ "m", "D" ]
run = "plugin bookmarks delete_all"
desc = "Delete all bookmarks"

# relative-motions
[[mgr.prepend_keymap]]
on = [ "1" ]
run = "plugin relative-motions 1"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "2" ]
run = "plugin relative-motions 2"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "3" ]
run = "plugin relative-motions 3"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "4" ]
run = "plugin relative-motions 4"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "5" ]
run = "plugin relative-motions 5"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "6" ]
run = "plugin relative-motions 6"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "7" ]
run = "plugin relative-motions 7"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "8" ]
run = "plugin relative-motions 8"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "9" ]
run = "plugin relative-motions 9"
desc = "Move in relative steps"

# jump to char
[[mgr.prepend_keymap]]
on   = "f"
run  = "plugin jump-to-char"
desc = "Jump to char"


[[mgr.prepend_keymap]]
on = [ "g", "1" ]
run = "tab_switch 0"
des = "tab 1"

[[mgr.prepend_keymap]]
on = [ "g", "2" ]
run = "tab_switch 1"
des = "tab 2"

[[mgr.prepend_keymap]]
on = [ "g", "3" ]
run = "tab_switch 2"
des = "tab 3"

[[mgr.prepend_keymap]]
on = [ "g", "4" ]
run = "tab_switch 3"
des = "tab 4"

[[mgr.prepend_keymap]]
on = [ "g", "5" ]
run = "tab_switch 4"
des = "tab 5"

[[mgr.prepend_keymap]]
on = [ "g", "6" ]
run = "tab_switch 5"
des = "tab 6"

[[mgr.prepend_keymap]]
on = [ "g", "7" ]
run = "tab_switch 6"
des = "tab 7"

[[mgr.prepend_keymap]]
on = [ "g", "8" ]
run = "tab_switch 7"
des = "tab 8"

[[mgr.prepend_keymap]]
on = [ "g", "9" ]
run = "tab_switch 8"
des = "tab 9"
